/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.parkinglot;

import com.parkinglot.factory.VehicleFactory;
import com.parkinglot.model.Car;
import com.parkinglot.service.ParkingLotService;
import com.parkinglot.types.VehicleType;

public class App {

  public static void main(String[] args) {
    new App().run();
  }

  public void run() {
    var service = new ParkingLotService();
    service.createParkingLot();

    var car = VehicleFactory.getCar("ABC-1234-56");
    service.parkVehicle(car);
  }
}
